# Generated by Django 4.2.1 on 2023-07-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, null=True, upload_to='image/')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('Price', models.TextField()),
            ],
        ),
    ]
